# Generated by Django 4.0.6 on 2022-07-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalPython', '0003_author_alter_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProveedor', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Provincia', models.CharField(max_length=500)),
                ('Localidad', models.CharField(max_length=500)),
                ('Direccion', models.CharField(max_length=1000)),
                ('Cuit', models.CharField(max_length=1000)),
            ],
        ),
    ]
