# Generated by Django 4.0.6 on 2022-08-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalPython', '0004_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoArticulo', models.CharField(max_length=8)),
                ('Descripcion', models.CharField(max_length=30)),
                ('Color', models.CharField(max_length=30)),
                ('Talle', models.CharField(max_length=20)),
                ('Precio', models.CharField(max_length=20)),
                ('CodigoBarra', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCliente', models.CharField(max_length=8)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Provincia', models.CharField(max_length=20)),
                ('Localidad', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=30)),
                ('Cuit', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numpedido', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('CodClie', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
