# Generated by Django 4.1 on 2022-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalPython', '0005_articulo_cliente_pedido_delete_author_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos'),
        ),
    ]
