# Generated by Django 4.0.6 on 2022-08-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalPython', '0006_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='DescripcionLarga',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
